### ISSUE TITLE
Connection String Secret

### ISSUE THREAD

**Issue by brettrowberry** [AngelMunoz/Migrondi#13]
How should I manage a connection string with a secret?

**Comment by AngelMunoz** [comment]
there's no support for secrets right now if you're trying to run from CI or similar you could save the JSON file (with your secret) as an env var and "echo" it into the environment before starting the migration phase. Something like

```
echo $MIGRONDI_CONF > migrondi.json
```
which is what I do on GitLab's CI, for example I do this with my gcloud service keys
```yml
...
deploy:
  stage: deploy
  script:
   ...
    - echo $GCP_SERVICE_KEY_STAGING > gcloud-service-key.json # Google Cloud service accounts
   ...
```

there are a couple of ways we can do this as well we can take them as cli arguments or try to read them from the environment
